### ISSUE TITLE
A simple question

### ISSUE THREAD

**Issue by 200huesos** [rscustom/rocksmith-custom-song-toolkit#198]
Hi all, Im trying to be an active member on Customforge, Im trying to change the audio on some custom songs that I already have on my dlc folder, I import the complete Psarc file and then change the audio file for another with no guitar on it, and change the names to .......no guitar_p.psarc and .xml etc., but when I put it on the dlc folder and open rocksmith, the song is only one, it's overwritten by the no guitar file, it works, but it have the same record percentage and the "complete band" song has been disappeared.
How can I do to have the one with the guitar and the one with no guitar? 
Thank you very much in advance!

**Comment by L0FKA** [comment]
Simply, you should readd arrangement\change dlcname and song name, in future we'll get support for multitracks so you could just select individual sound file per arangement, but for now it's ok to go that way, hope you'll get it.

**Comment by 200huesos** [comment]
Thank you very much for your support, but I have already done this
![custom](https://cloud.githubusercontent.com/assets/10488826/5696796/f2a5b12c-99dc-11e4-9545-27e84f711d31.jpg)

**Comment by cozy1** [comment]
Answered by Lofka  You need readd the arrangments to change the Arrangment Identifier.  Or you can click on each arrangment then click edit, then increment the arrangement identification number last two digits and hex value to something else.  Make sure it is the same length and valid hex.

**Comment by 200huesos** [comment]
Thank you very much Cozy1 !!!

**Comment by cozy1** [comment]
New release of toolkit will automatically increment arrangement id when you change any of the song information in the package creator gui.  Simple as changing the version number will give you a new arrangement id.  So you do not need to manually change ids anymore.

**Comment by otaznik** [comment]
So you say that you broke Arrangement ID feature.  It's the purpose of it to be unique and never change for a song.

**Comment by L0FKA** [comment]
According to user reports we often had same ID issue for arrangements, so this is how we "fixed" that issue, but I think we should add option or preserve ID's manually.

**Comment by cozy1** [comment]
I believe current toolkit behavior is that if nothing is changed in Creator GUI then the appid is reused, or at least that is how it should be.  But if user changes any of song info then a new appid is created to prevent in game hangs and conflicts.

**Comment by fabianosan** [comment]
Guys,

I have to agree with @otaznik , for me the Arrangement ID is a feature, not an issue.
Maybe a button to the user (song creator) can choose to change ID if he want.

If we choose to make it automatic, at least define to change only if some key information are changed, not any field as @cozy1 said.

I suggest:
If "DLC name" field changed, we will change the ID of each arrangement in the song, and show an alert for user confirmation;
For specific arrangement, only if the XML definition was changed.

**Comment by cozy1** [comment]
Changing/updating the AppId when a CDLC is revised has eliminated many of the previous in game hangs.  The user game save _prfldb stores song and stat information based on the CDLC's AppId 'GUIDs'  When a CDLC Charter changes the DD, ebeats, phrases, or pretty much anything else inside the XML that happens to be also stored in the _prfldb, there is a potential for disconnects with the data that ultimately leads to in game hangs.  Since I implemented the automatic AppId updates there have been far fewer in game CDLC crashes.  That said ...
I do not disagree that there could be an option (checkbox) to leave the AppId unchanged but be aware there are risks in doing so, i.e., in game hangs.  I will implement a checkbox option to leave (force) AppId unchanged in my next commit.  Thanks guys for input.

**Comment by cozy1** [comment]
Curious ... this was implemented in April.  Why the sudden interest?

**Comment by fabianosan** [comment]
I'm not an active contributing to the code at this time, but I still using app and playing Rocksmith in my free time. And don't get me wrong, I check almost all commits you do, I get notifications.

My interest on this, is because I use this feature, most of the CDLCS I download due to poor quality and I adjust and repack the song many times.

**Comment by cozy1** [comment]
@fabianosan So it looks like you would prefer a popup alert with user confirmation to change Arrangement ID when Generate button is pressed, instead of having a continuously displayed checkbox.  Is that right?  I can implement in my next commit.

**Comment by fabianosan** [comment]
No, I did not think about checkbox before, sorry. Checkbox maybe is a better way.

**Comment by cozy1** [comment]
Just tried popup and it looks ok.  Popup maybe better because it does not clutter GUI and it provides more information about why it is important to change Arrangement IDs.  I will commit and you can have a look and see if you like it.

**Comment by fabianosan** [comment]
Thank you.
