### ISSUE TITLE
Toolkit Won't Launch

### ISSUE THREAD

**Issue by artyonet** [rscustom/rocksmith-custom-song-toolkit#243]
I've downloaded the latest version of Mono yet it keeps telling me to I need to get at least vesion 2.4 or better. I downloaded version 4.2 or something. I don't know what to do. I'm very new to this. 
![screen shot 2015-09-30 at 6 18 11 pm](https://cloud.githubusercontent.com/assets/14905748/10210770/4001b6d2-67a0-11e5-9da6-525f88b57cdf.png)

**Comment by Baggie95** [comment]
Same issue here, can not get it to work at all, even with alpha versions of Mono. Im running on OS X 10.11.1 Beta (15B22c)
![mono version](https://cloud.githubusercontent.com/assets/14937981/10242655/4c417612-68ea-11e5-8eba-6e95f657c36f.jpg)

**Comment by ray** [comment]
This is not a toolkit issue, but is a Mono and/or OS X issue.

My understanding is there are multiple problems that could be happening here:
1. Mono not adding itself to the path properly. Older versions of Mono may work. You might also be able to fix this with `sudo ln -s /Library/Frameworks/Mono.framework/Versions/Current/bin/mono /usr/bin/mono` (you may need to do the next step if you get a permission error)

2. Issues caused by System Integrity Protection. You may be able to fix this by:
- Reboot your computer and hold down Cmd-R to boot into recovery mode
- Open a terminal and run `csrutil disable`
- Reboot and re-install Mono
- Once Mono is installed, go back into recovery mode and run `csrutil enable` to turn SIP back on

If that still doesn't work, you'd probably need to check with the Mono community for further assistance. But it's not a toolkit issue and not something we can fix.

**Comment by Baggie95** [comment]
Hey,

Just wanted to let you know that your suggestions did help to fix the
issue,

I had to Disable the SIP first of all, reinstall mono 4.0.4.4 and then run
the sudo command, and hey, it started working :)

Thanks for the help, and I just wanted to let you know how I managed to fix
it, just in case someone else has the same problem.

I also have a small suggestion/request, is there any chance for bulk
conversions? I usually play on windows, and have way over 1000 songs. I
recently got macbook just for fun and wanted to move my library over, but
one by one takes a veery long time :(

Again, thanks for the help!

**Comment by PhonneyHook** [comment]
Didnt worked D:

**Comment by PhonneyHook** [comment]
i disabled the ( csrutil disable ) and reinstall the the Mono framework 4.0.4 and enabled ( csrutil enable ) and still say the same D:

**Comment by surrealchemist** [comment]
The installer generates the symlink as /usr/local/bin/mono 

I don't know why your startup script can't detect it, but if I just go into the resources directory and run mono on RocksmithToolkitGUI.exe it loads. 

I don't think it is unreasonable to have the application load in a way that doesn't require you to modify system wide security settings and reboot in order to make it work.

**Comment by ray** [comment]
If Mono isn't installing itself properly and isn't inserting itself into $PATH, that's a problem for the Mono team to fix, not us. It's not our problem to fix.

In any case, we already add /usr/local/bin to the path ourselves as of c0d65de

**Comment by surrealchemist** [comment]
I guess I should have tried the 2.6.1 build before commenting, that seems to work without issue. 

At least anyone else finding this discussion will have that information now.

**Comment by krisring-taulia** [comment]
Running OSX 10.11.3 and having this issue - I have used every version of mono that has been suggested - and I'm not really willing to disable the SIP on my system - has there been a real solution found to this yet?

**Comment by seaniepie** [comment]
@ray , if mono is a problem then this IS your problem as you USE mono to get your software to work. I would suggest looking into using something a little more robust than a piece of software Mono is unwilling to upgrade. If we can't use Mono then we can't use your toolkit - aka YOUR PROBLEM.

**Comment by seaniepie** [comment]
OSX has done a major clamp down on use of the usr/local path. I would avoid using this at all costs. Find another way people. Or your software will become very quickly unusable.

**Comment by seaniepie** [comment]
Why is it that 2.6.1 works ok but your 2.7 build does not? What have YOU changed because the Mono framework is the same.

**Comment by L0FKA** [comment]
@seaniepie, don't be and asshat, please. Just complaining\whining "it shitty pice of bytecodes doesn't work, kill yourself RSCustoms" won't help to solve your issue with toolkit, I'd suggest you to launch this app through terminal and send us it's output also if it works with older version you should specify build hash for it for a reference (I'm talking about that magic number after 2.6.1.0- )

Thus "advice" to use unknown "better solution" won't help much, if you need full toolkit feachpack use windows instead ;)
Support for macOS (as it renamed now) is partial and only useful to change appid and (un)pack\repack cdlcs's.

**Comment by HTmfG** [comment]
I'm lost. I'm on a Mac running MacOS El Capitan 10.11.6 using RockSmith Remastered (Purchased CD) playing through Steam built Oct 12 at 17:51:26 Steam API :v017 Package version 1476379980

I don't know how to do this step:
1. Mono not adding itself to the path properly. Older versions of Mono may work. You might also be able to fix this with sudo ln -s /Library/Frameworks/Mono.framework/Versions/Current/bin/mono /usr/bin/mono 

I go through the path and open mono and I can't type anything. Can some one please help me? and tell me what I'm doing wrong or what else I need to do?

I have rebooted to the recovery mode ran the "csrutil disable" command rebooted and installed the latest version of MONO and rebooted to recovery mode and ran the the "csrutil enable" command. Rebooted and I have the same issue when I try to start the toolkit. 

I can see the CDLC in my Rocksmith remastered game. I get through he tuning, but then there is nothing there just an image of speakers and I can play my guitar through the computer, but that's all. I can't even get out of the game without quitting.

Thanks in advance,
-H

ref: https://github.com/rscustom/rocksmith-custom-song-toolkit/issues/243
