### ISSUE TITLE
Convert bug

### ISSUE THREAD

**Issue by hajdbo** [rscustom/rocksmith-custom-song-toolkit#254]
Chicago Music Exchange "100 riffs" is a very good torture test for converting PC->Mac.
With build 202 (and previous), convert fails.

cdlc file:
https://www.dropbox.com/sh/q60kxywkolkwdva/AAA2nUnsoIZSTcrLmtSbCLtKa?dl=0

error screen captured here:
http://imgur.com/kahmIsb

**Comment by cozy1** [comment]
@hajdbo We have seen this error before.  Usually with conversions.  See if these help you fix it:
http://customsforge.com/topic/23579-end-of-stream-reached-with-4-byte-left-to-read/#entry181461
http://customsforge.com/topic/25808-error-generating-ps3-xbox-files/#entry195966

Please confirm whether song has a BPM issue.  Also remove DD before trying to convert.  Let us know if this helps you convert song.

**Comment by hajdbo** [comment]
I'm not sure I can, since "Import Package" also breaks on this file.

**Comment by cozy1** [comment]
I am able to reproduce  "End of Stream" error when converting.  Import Package works on PC.  I will take a look

**Comment by cozy1** [comment]
@hajdbo  The song you are trying to convert is broken.  PM me on CF.

**Comment by L0FKA** [comment]
Unfortunately it's sng decryption bug+converter because it's unable to set source platform and it though that sng uses MAC key but it's true key is PC so we've got mess of bytes instead, since that bpm section is first in sng format which breaks in first place, so all we should do is improve detection for decryptor, I see you go easy way and did "try\catch" there... reopen this, since it's not fixed and all songs will fail to convert under mac, unless it's not console>mac conversion, I suppose.

**Comment by hajdbo** [comment]
Running CustomSongToolkit build 202 on Mac + Mono: most songs convert PC->Mac just fine. This particular one does not.

**Comment by L0FKA** [comment]
Sng files seems to be fine, anyways it converts fine pc>xbox fast convert fails anyway.
what songs you successfully convert from pc 2 mac?

**Comment by hajdbo** [comment]
Most files convert PC->Mac just fine using mono on a mac.
For example, this one with build 202 converts fine: https://www.dropbox.com/s/e42nq87nrwfysq1/JamesBondTheme-20140225-2019_p.psarc

**Comment by hajdbo** [comment]
However, "Import Package" does not work on this JamesBond file (using my Mac and build 204)

**Comment by cozy1** [comment]
@L0FKA The songs that @hajdbo are trying to convert are broken (have incomplete song information because the original charters failed to enter it).  This blows up during conversion in tk.  See my comments here:  https://github.com/rscustom/rocksmith-custom-song-toolkit/commit/1e076a5e46deb903e03384f1b9993178226b5115

IMHO this is a song/charter/old toolkit issue (because tk did not validate song information) and not a current toolkit issue.  If you think it is current toolkit then plz fix it cause I am not seeing it.

**Comment by cozy1** [comment]
"Running CustomSongToolkit build 202"  This is old, need to make a new version of this from latest build.
