### ISSUE TITLE
CustomsForge

### ISSUE THREAD

**Issue by Unleashed2k** [rscustom/rocksmith-custom-song-toolkit#259]
@ray & others I was wondering if it's possible that CustomsForge could acquire/help this project at all. It would run exactly the same but we could update the website / etc (such as http://editoronfire.com & http://cfmanager.com). Also If any area is lacking we can find spots to fill. 
Let me know what you think and if you have any questions or concerns. We would just assist on bringing extra resources to the project. We already work with raynebc and allow him to do everything 100% freely on EOF but maintain his website / assist on anything he needs.

**Comment by fabianosan** [comment]
@Unleashed2k I believe that this project is not on sale, because this project has the free contribution of many good peopl, but any help is wellcome.

@ray What you think about it? It's your decision, maybe we can listen @Unleashed2k to understand what he think with help...

**Comment by Unleashed2k** [comment]
I wasn't actually planning to "purchase" the project but acquire it and let you guys run it like you already are.

We would do the following:
1) Update the website 
2) RSTK would comply under our "creators" project we've been working on.
More details on "Creators"
A whole section of CF dedicated to CDLC creation. This includes CFSM deploying the latest versions of RSTK and EOF.
You can still get both projects individually, but CFSM would keep EOF up to date and make sure you're running an up to date RSTK*.
*This would not compete with the autoupdate feature, if you point to RSTK and it's a very old version it would basically give you a warning that you should update.
3) Sponsorship. The project would be sponsored every month and if you needed something such as zenhub (zenhub.com) or a private project under github we could supply it.
4) Communication. It is 100% optional but the staff could join our CF Slack where we discuss a lot of things behind the scenes and make important decisions.
At the moment our staff is testing the next version of our website and you could provide direct feedback.
5) Ignition. The toolkit could use our new API to work with the website. 
6) Teamwork. We have various people on our staff working on several projects that could help contribute. You could cross-contribute to our projects as well.

We want a better rocksmith custom experience for everyone and I believe we could definitely help.

**Comment by ray** [comment]
Agreed with fabianosan. This is an open source project that belongs to the community.

Various poeple like fabianosan, L0FKA, cozy1, etc have organically taken on lead roles and I'm sure others will in the future too.
None of us started the project or own it any more than anyone else does.

If you have people that want to contribute, they're already able to.
If you want to take on a leadership role and identify areas of opportunity and submit issues, you're more than welcome to.
Acquiring the project and claiming ownership over it doesn't really change how you could help if you really wanted to.

**Comment by Unleashed2k** [comment]
A huge part of that community (169k members, with 100+ registration per day) is directly from the result of CustomsForge within the last few years.
The whole community owns all of these projects because without the dedication of the toolkit creators, the website developers, and the (EOF) editor we wouldn't have customs in Rocksmith.

My plan was to never to take the project away from the community, I am doing the exact opposite and trying to improve what's already there.
Every project needs a solid leader. 
If you've been to TheRiffRepeater lately that was directly the result of me teaming up with them and improving everything that could be improved.
(Updated website, migrated it to a new server, increased his ad profit by 80%, fixed bugs and other various issues). Yet it is still 100% his project that he owns.

The company that owns CF that I run - http://unleashed2k.com/ would be managing (as of now it's me plus the CF admins/board members) but other staff of CF could still assist if needed.
As listed above in my previous post we already have an outline of what we would like to improve on the project.
"Acquiring the project and claiming ownership over it doesn't really change how you could help if you really wanted to."
With what we can provide it actually does. We would need to modify the DNS for rstoolkit.com to run under cloudflare so we can launch a new website beta and test new features.
Additionally to provide enhanced github features such as Zenhub we would need an ownership role to pay for these options.

If you went with this and didn't like the direction it was going eventually, you could simply revert the DNS changes and revert any other changes upon agreement. 

I'll be completely honest that I will be disappointed if we can't find a middle point here as I personally do not see a downside to this.

My portfolio:
http://editoronfire.com - Website design & backend file management
http://customsforge.com - self explanatory. We revived SA's community and improved it 100% with new features and an updated website coming soon. 
http://cfmanager.com - Our own manager for DLC management with the help of @cozy1 and others.
http://theriffrepeater.com/ - A website which was crashing constantly and other problems, we fixed it up and made it better under two weeks.
http://twitch.tv/windofthestars - Professional Twitch Management for a VIP Cosplayer who has been featured in several web publications such as CNET, Nerdist, TokyoPOP, and Kotaku. She has made professional costumes for Game of Thrones.
& other various twitch streamers and projects we help co-manage.

All of these projects besides CF & CFM have are still owned by the community or whoever we're assisting (elliot [TRR], mel [windofthestars], raynebc [EOF], etc)

**Comment by Berneer** [comment]
CF belonging to a company? board of directors? acquire?

I have to be honest, it is challenging to get past those words for a labour-of-love community project.

There's no denying you've done amazing work Unleashed2k and we are all extremely (!!) grateful but it's difficult (at least for me) to see how the community is significantly improved by these proposals.

You seem to want to change something that is not broken and neatly all currently resides in CF and Gihub. Perhaps more elaborated visuals of how this integration proposal will benefit the average community member might make the community more receptive to your possibly brilliant ideas. A list of pros and cons also helps everyone understand. Just seems like the way things work now is quite efficient. 

cozy1, raynebc, lofka (Alex360), fabianosan, do you see any near-term to medium-term need for funds to overhaul the softwares you manage? If so then I guess I could see why using CF donation money would require the softwares to be acquired. Otherwise, to remain web-site-agnostic, I would imagine a kick-starter campaign could be started. I often wondered and dread, for example, what we would do if ever raynebc grew tired of maintaining EoF. In such a case I guess there is another benefit of the software being acquired.

However, as you know CF is not the only Rocksmith CDLC site. EoF and the RSTK is openly shared and supported on more than just the CF web site. How would your proposal affect that. Example, I certainly don't expect to see CF Song Manager on another site because it was developed by CF. Would other sites still be allowed to offer and support these proposed-acquired-software?

I've never run a forum or web site that involves donations before, so I apologize if I am just speaking out of turn and with incomplete fluency with the technical and logistic stakes involved. But as ray (I presume that is raynebc) said, since it is an "open source project that belongs to the community" I'm not sure how one goes about negotiating with a community....especially when the tools serve multiple non-fully-overlapping communities.

When you say: "If you went with this and didn't like the direction it was going eventually, you could simply revert the DNS changes and revert any other changes upon agreement. " what do you mean by "upon agreement"?

Again, Unleashed2k, you have accomplished amazing things for us and helped our community to flourish so please don't see my comments as antagonism but more like responsible questions from an average member like me who thinks, perhaps naively, that this needs to remain non-profit and open and most of all a long-term community where we can enjoy our interactions for many years to come.

Cheers,
Berneer

**Comment by raynebc** [comment]
ray is a separate member.

As far as EOF goes, it's generally a cost-free program from the perspective of my involvement.  It doesn't require any significant amount of resources to develop, since all the development software and tools I use are free and/or open source.  I can set up a physical Linux box if I ever had to do any significant troubleshooting on that platform, but I think the number of *nix EOF users is probably extremely small compared to Windows or even Mac users.

I wouldn't worry about me giving up on the developing it anytime in the near future.  Over the past 6 years, I've gone through times of light development and times of heavy development, depending on what features I or the user base decide is important or useful.  Even if I ever went on a long enough hiatus for people to notice, the program is open source and could easily be forked.  I use lots of comments in the source code, which I hope is relatively straightforward itself.  I don't expect it would be terribly difficult for somebody to replace me if it ever came to that.

As for the toolkit, I'm not a very business-savvy person so I'm not sure what benefits there are to one person or entity assuming ownership of the software compared to having it remain more or less completely unowned and with each person contributing to it as they do now.

**Comment by Unleashed2k** [comment]
Well case in point is the EOF project. We help develop your website and keep it up to date. http://editoronfire.com -- you still work on it and provide it to other websites and uphold the other features of it (bandfuse, FoF, etc) and you run it 100%. If you needed a software license we would get it for you.

I understand what I said in the beginning of my last reply can be confusing / overwhelming.  it is not just about that. It's about being able to provide and bring to the table additional features. I actually misworded my original proposal. Acquire is a harsh term to use as it the word is used to "own" and "take over a project". I'd rather use the term manage the project but still be owned in the eyes of the community, exactly on how we help EOF and other projects. Money is just a pro that we can offer if something is needed we can provide it (anything from domain renewals to software licenses and servers).

A Kickstarter is definitely not needed. I really personally cannot think of any cons of this partnership. We would be assist on anything and everything yet it would still be run by the community. Like I said we would just help manage and assist the project. The current contributors would do exactly the same thing.

Pros:
Financial Assistance if needed
Still run by the community
Still able to do different games if needed
Ignition API integration
Updated Website
Possible better documentation and updated info
Deployable by CFSM
Cons:
???
I would need to hear the cons as I don't personally see any. This just benefits the community. I gain nothing for helping any of these projects, I do it out of passion.

**Comment by Berneer** [comment]
Hi guys,

Thanks for the feedback Unleashed.

I guess I have a few questions:

1) Just curious? Can you elaborate on how you envision having dedicated Editor on Fire and RSTK websites improves upon the current way of doing things from a community and devs perspective?  

2) Can you elaborate how integrating EoF and RSTK into Ignition is beneficial apart from the obvious mod/repacking of customs on the fly?  Like DDC, would the softwares be integrated yet still accessible as standalone? 

3) Apart from the already stated pro's you already listed, can you give a few concrete examples of projects and improvements to the way devs and end-user community members currently do things that only become possible with this proposed partnership in place. Walk us through your vision please in a "Wouldn't it be great if we could.... ?". I know I'd personally love to get all excited about your new ideas. I'm sure your examples will help people get on-board and be enthusiastic if they deem it having widespread appeal.

4) If the community decides that this partnership is restrictive or undermining development due to the partnership then can you outline how partnership dissolution will take place? If Customsforge were to cease existing, how would it impact EoF and the RSTK continuance?

5) I guess Ray is CF member cozy1 or Dreddfoxx or...? Curious.

Just questions to help understand the stakes involved so the devs/community can make an informed decision. I know there are things I know not to ask.... so devs.... I defer to your judgement and will get out of your way, if asked since this is a developer's forum. Just thought that as an interested community member that requesting elaboration would help give Unleashed2k's idea a fair shake.

Cheers,
Berneer

**Comment by Unleashed2k** [comment]
1) I actually ran a few tests with this. Before CFManager had a dedicated website it was getting about 5-10 downloads per day. After we launched the website it moved up to around 500+ per week which is a huge jump. We provide screenshots of the app and soon will provide more. This helps the user visualize the app. The devs focus heavily on developing the apps. A basic github website can be straightforward yes, but if you want more people using your tools, having a full website with pictures and documentation can bring more users to use the toolkit.  Better documentation/guides/tutorials on the website as well can help users use the toolkit the correct way and make sure they keep it up to date.

2) EOF won't be integrating into Ignition as I don't see a reason for it. But RSTK can definitely do it, there are multiple endpoints in our API for options. We're in talks with a spotify developer to integrate their API with ours so we could pull album data and help autocomplete fields if we wanted to. There's so much we can do.

3) 
Wouldn't it be great if....
.... we had full documentation created with visual and text guides
we're able to pull album art and other fields automatically if the user chooses this
a full visual website where users could preview screenshots of the app
get more up to date changelogs on the website (the latest news has a 2+ year gap..)
have the developers use zenhub for better organization of github? (example: http://thenextweb.com/wp-content/blogs.dir/1/files/2014/10/01-ZenHub-Task-Board-Kanban-styled.png)

4) We would revert all changes unless the team wanted to keep the changes, then we would donate them free of charge and they could continue to do as they please. (Website could be reverted easily, for example... any integrations could be removed via code changes). EOF and RSTK could still live without CF. Another website would pop up. But I don't see CF going away as it's my passion to keep it running and improving it as much as I can. Which is why I'm working with you guys in the first place, to tie the community together more and help new users get into creating customs and making it easier for them.

5) I don't know to be honest. Just a dev at this project afaik. 

I would like to add that I really appreciate a community member such as yourself coming here and asking questions. My end goal is to get tons of new users to use the toolkit so we can have better and more customs. A long time ago I actually pushed for the toolkit to have an update function. That has caused users to keep the toolkit up to date with the latest fixes. I want this more as a partnership with us allowing to help manage some things while the devs continue to do as they please.

**Comment by Unleashed2k** [comment]
The project here is great and I absolutely love it, don't get me wrong. I just think we could improve it all together.
As of now: 

Basic github website that is barely updated (2+ year gap on changelog)
No screenshots
No documentation
No API points to ignition
No importing information from databases (last.fm/spotify/wikipedia, etc)

In the future:
A fully updated website.
Screenshots of the app for people to preview before they download
Documentation on how to properly use RSTK
Optional API integrations 
Latest News updated more often.
Integration with CFSM where it can be installed/deployed from the app*
(*EOF has approved this feature already, waiting for okay from RSTK devs)
Still it's own independant project run by developers of the community
Money funding available

**Comment by papillon-rs** [comment]
I really don't understand why they have to become CF projects and be integrated into one website. There're other websites using the same tools to create their customs - it should be standalone tools and not connected to one website. 

The RSTK is hosted here for free and everybody can checkout the files and help (if having the programming skills). If there're more resources (people writing code or writing documentation) you don't need to change to paid services. With more paid services you'll need more donations and I don't think that the willingness to stretch the donation amount is unlimited. 99% of the users just want to download good customs and play them in Rocksmith.

Which additional meta data is necessary? If the audio file is tagged correctly you get the meta data and downloading the album cover takes a few minutes. Or is it additional information to be displayed on a website? 

The question would be - are you (the developers) missing a feature in the free hosting or tools you're using or do you need licenses.

Thx for all the work to make it possible for us to play customs. 

@Unleashed2k I appreciate the work you do on CF and this is a constructive critique - there's always room to improve things or adding new features, but not everything will improve customs or is useful for the majority of a community. With any integration of RSTK you'll not get high quality customs and there're are probably many threads with instructions or hints using the tools. There's probably not a lack of features, but a lack of feedback. I felt very sorry for some people when visiting the site and these people posted a lot of customs without any comment or thx but 300+ downloads.
For some points - writing a good documentation, providing the download link of a release - you don't need ownership of a project and if there're equivalent free services or tools they should be preferred for an open source project. Not all bells and whistles of commercial alternatives are necessary and will not write better or more code.

**Comment by Unleashed2k** [comment]
This would not become a CF project, it would be a separate entity on where we would assist. It would be me personally becoming the project manager I guess you could say, and I would update the website/changelogs/etc since it's not being done at the moment. CF staff will of course assist. The website design MAY be hosted on one of our servers if github pages won't allow the bootstrap update but it won't be under the CF ignition setup. "with more paid services" Actually because the way github is setup I could add them to my existing plans. You can take a good look at customs and see incorrect spellings of CDLC, bad album artwork etc. The PRO CDLC creators, of course, know what they are doing. You need to look at the basic user who doesn't and wants to start using it. Everyone is missing the main point here. It's not about the paid stuff, that comes WITH the package of working with us. That is beside the point. The point is an updated website with screenshots and proper documentation which is very important. I have to keep on bringing up EOF but EOF is a perfect example. raynebc posts on multiple forums and works with users on their problems. He does a changelog on each update and posts it. His website has screenshot of the app as well. There was a 2 year gap between a stable release. Our staff a CF had to push for that to even happen, if it's run by the community you guys should have updated the stable release years ago. With proper management, that would have been taken care of. Metadata is an additional feature that we could help provide. I think all the main people are getting the wrong picture here unfortunately and it sucks. I can't get my point across successfully and not sure what to do. I'm launching a survey at CF to gain feedback on the RSTK project to see what they think. 

Let's reset for a moment.
I (unleashed2k) want to take this project here and help improve it. The CF Staff would be able to help assist on the project of course. My goal is a website overhaul and possibly add new features from github to the app. With better management, the project could get into the hands of new users and they can get proper documentation and information. We can see what features we are lacking, what we need to do and how to improve upon it. This has been in the motion for months. I've been sent feedback from plenty of users about the website and I told them I don't run it and to ask you guys about it. But I provide support if I need to. Example feedback I've seen is there isn't a clear response from any RSTK dev on what is going on or what they are currently working on. The project is leading blindly from an outside user's perspective. I want to be able to provide updates to the users who use your project and let them know what's going on. Visual aid and communication are key. 

I don't see what people are scared of unless it's change, or laziness. I'm not your enemy here. We need to work together here and make this project better than what it could ever be. It's a great project but it can be even better if we put our minds and the community together more.

**Comment by fabianosan** [comment]
@Unleashed2k
> For RSTK, there was a 2 year gap between a stable 

It's not really true, the beta releases are almost stable releases and the "stable" releases in this case is only a nomenclature, even because all users are downloading the latest versions and it works fine.

And the code that's most important is constantly updated and maintained by developers.
The RSTK never left alone community since RS1 and if Ubi releases new versions; w'll you work hard again to make it always fully functional for us.

>Basic github website that is barely updated (2+ year gap on changelog)
No screenshots
No documentation
No API points to ignition

You or any developer can fork this project, and develop what you need and submit a pull request that we can add to main code.
If the developer remains active and making good work, he will be integrated to the main team too if he desire.
Documentation, changelogs, etc, can be updated too, need just do the work and submit.

> I (unleashed2k) want to take this project here and help improve it

Same as above

> Money funding available

We have no interest in it.

@papillon-rs 

> 99% of the users just want to download good customs and play them in Rocksmith.

You are right in all of your words...

@ray I'll close this topic, because I believe that the dialog will not be productive.
Feel free to open again if you want.

@Unleashed2k Thank for your amazing work on CustomForge, I love the forum, it's better than smithanvil, keep doing this great job.

Feel free to join us in this project and extend this invite to all your developers, you can do all improvements that quoted on this topic, but keeping the essence of this project the same when it was started four years ago.

**Comment by Unleashed2k** [comment]
https://i.gyazo.com/85761c0ab8454556eb8979d99f345200.png

**Comment by fabianosan** [comment]
News is not important. You are able to generate customs? Convert customs? And use all self explanatory features of the tool?

And again, feel free to write the news and send to us if it is your concern.

**Comment by Unleashed2k** [comment]
I am, yes. I learned by tons of reading. But the general new user doesn't. Most new users give up. I provide support for your app all the time on Discord and other channels. I personally teach people the proper and best way to use it. 

Example questions.
WEM ERROR?!!? what do I do???
Bass fix! How do I use that?
What's the SNG tab?
What's ziggypro? Is that zippyshare?
How do I set my username?
What is WWISE?

Or hell, a better example... is a forum I created for you guys:
http://customsforge.com/forum/56-rocksmith-custom-tool-kit/
...9 pages of problems that could be fixed with a simple FAQ and documentation. 

I rest my case and you can keep this closed, we will find a solution another way I guess.

**Comment by fabianosan** [comment]
99% about of questions is not about RSTK, is about customs and includes a tons of tools include EoF, Wwise, etc.

Exactly what you said, a simple guide and a FAQ solves the problem, do it, post a topic on CF forum and voilá, the problem has gone, is not dependant of this project. 

Open a issue with each improvement that you are suggesting that we certainly will work on this or just do it that will very welcome.

**Comment by zerkz** [comment]
I agree that it should be separate from CF as well. Many fansites/modding sites do not have a forever life (github seems to, though!). Software development is always easier whenever your scope is smaller. Let's face it, the tools out there for the rocksmith scene (including customsforge) are not bug free/able to recover easily all the time. Let's not have a bug break the functionality of an entire suite of tools. 

@Unleashed2k one thing you could do is have a button that simply opens the toolkit for whatever functions you need. If the hassle of opening up the same song/directory is a big deal, maybe extending toolkit to take cmd line args would allow you to easily work in the same context across both tools.
