### ISSUE TITLE
Beta Server Link is Down

### ISSUE THREAD

**Issue by cozy1** [rscustom/rocksmith-custom-song-toolkit#265]
@ray I am currently working a problem with appveyor and notice the beta release link on rscustom.net is missing/down.  Could you please work your magic and reboot/fix?  Thanks

**Comment by ray** [comment]
Done, updated the code to ignore failed builds

**Comment by cozy1** [comment]
@ray  I am a little stuck.  I don't understand AppVeyor.yml enough to see what I am doing wrong here: https://ci.appveyor.com/project/rscustom/rocksmith-custom-song-toolkit/branch/master  I didn't change anything in yml.  Your help is appreciated.

**Comment by cozy1** [comment]
It looks like yml is failing at the  'after_build' section aka code signing.

**Comment by ray** [comment]
I'm not sure if I'm seeing the same log as you because I'm not seeing anything to do with after_build.

The log shows "Specify which project or solution file to use because the folder contains more than one project or solution file"

This is because 29b1664d added a new solution file RocksmithToolkitCLI/remastered/remastered.sln so Appveyor doesn't know which one to build.

I'd personally just remove that sln and add it as a project to the existing solution instead.
Or in the yml you can add to the build section something like:

```
build:
  project: RocksmithCustomSongCreator.sln
```
However that will obviously break the build if we ever rename the solution for whatever reason

**Comment by cozy1** [comment]
Oh, I got it now.  Thank you ... thank you.   I left the *.sln in the repo and committed it.  I will remove as you suggest and try again.  Perfect.

**Comment by cozy1** [comment]
@ray  Man ... that took me a while.  I had too many missing dependencies.  Green light now ... all is good again.  Thanks for help.
