### ISSUE TITLE
Add support for Japanese artist name and song title

### ISSUE THREAD

**Issue by iminashi** [rscustom/rocksmith-custom-song-toolkit#292]
There should be GUI fields for adding Japanese artist name and song title which will be displayed when the game is played in Japanese.

The pertinent attributes in the manifest files are _JapaneseArtistName_ and _JapaneseSongName_.

In Hotei - "Bambino", for example, the attributes are used in all the arrangements, but for the vocals they aren't really necessary, as B'z - "Giri Giri Chop" doesn't use them in the vocals arrangements.

**Comment by L0FKA** [comment]
Hai haiii, Arekkusu desu~

I'm dreaming about JVocals and It's been a year and half already, still I have Jvoc support for transcoding(not creating) officials, just to map out GUI for future custom songs.

How you see Japanese naming in Toolkit's GUI? maybe I should add those fields by checkbox in config, since It's not commonly used? or should I just do romanizator for kanji? maybe just flip\flop field from english to Japanese representation? I need help in deciding UX for this that's the only stopping factor for me for now

**Comment by iminashi** [comment]
How exactly it is implemented doesn't really matter to me. I'd be OK with a checkbox that enables it.
I wouldn't go with a romanizator, since people doing Japanese customs already know the romanizations, or they might want to use specific romanizations/translations anyway.

**Comment by L0FKA** [comment]
@iminashi japanese song name is there, not sure about artist name, can you give me an example of that? I know girgiri chop has Japanese kanji in it's name would like to poko ODLC with kanji in artist name :)

**Comment by iminashi** [comment]
"Yasashiku naritai" and the songs by Hotei have Japanese artist names.

**Comment by L0FKA** [comment]
Actually golden bomber has it's japanese names too so I can play with it, gotta push rest tonight :)
Thanks for w8ting :D
