### ISSUE TITLE
"System.UnauthorizedAccessException"

### ISSUE THREAD

**Issue by lbyrne2000** [rscustom/rocksmith-custom-song-toolkit#311]
Whenever I launch the Toolkit (I'm on Mac btw) an error message appears saying the above. It says that it is denied access to "/private/var/folders/w0/q_n1ykm50qz56h3bvp5dcrhc0000gn/T/AppTranslocation/6B311C21-469A" and then cuts off. Any ideas on how to fix this?

**Comment by JustinAiken** [comment]
Post output from when running from the CLI: 

```
$ /Applications/RocksmithCustomSongToolkit.app/Contents/MacOS/RocksmithCustomSongToolkit
```

**Comment by L0FKA** [comment]
any bump on this @lbyrne2000 ?

It's because we're using app bundle folder to write things there as tmp path, at least when you convert your ogg files to wem it will need to unpack template into toolkit's dir and so on some other apps are using toolkit's folder exclusively 
ref issue for the guy here https://stackoverflow.com/questions/26828532/iphone-unauthorized-access-exception

**Comment by JustinAiken** [comment]
> I won't support any newer MacOS with mono other than El Captain, since it's too much changes to OS itself

I'm on Sierra 10.12.6 with mono 5.12.0.226 and it's working for me :D 

...but yeah, the wineskin release is probably a much better/easier option for most

**Comment by L0FKA** [comment]
Due to no user activity and our wi e port released Im closing this
