### ISSUE TITLE
Original DLC XML -> SNG

### ISSUE THREAD

**Issue by Baoulettes** [rscustom/rocksmith-custom-song-toolkit#318]
Seem when you want to unpack original .psarc song as XML and edit example vocal or even without touching the files and you want to pack it again it corrupt some part.

Here on Bulls on Parade all palm mute got change to normal chords. (only accentuated chord should be visible and not muted.)
![boperror](https://user-images.githubusercontent.com/6192320/42833765-6ba9577a-89f5-11e8-95dc-094333a0244d.png)

Using V2.8.4.1-82e47ea8 BETA

PS: Doing manipulation on original dlc because I want to do different version for personal use that will fit my need example changing tuning because I do not own a guitar will handle well enough a certain tuning and I still want to learn once I will be able to have that tuning :)

**Comment by L0FKA** [comment]
@Baoulettes V2.8.4.1-82e47ea8 BETA is not BETA any more it's legacy now. I'm sure things didn't change much as for sng part but we surely improve on xml side and fixed some link next bugs... You can try latest build and see if it's still affected or not, I always suggest to use beta builds since fix for the issue someone's got may be fixed :) 
report back. we'll try to figure it out,

p.s.
 pm me about your findings for inlays and if you've got anything special? I'd like to play with it a bit more :)

**Comment by iminashi** [comment]
I found out what the issue is and I am testing a fix.

I never realized that ODLC and CDLC use "high density" so differently.

**Comment by Baoulettes** [comment]
@L0FKA At the moment I can not test it but later in the day I will try with lastest stable release.

About inlays I do not have made any progress that deserve talk ^^
Only one basic things that is far from being mandatory :p 
I will see where I did put my notes to see if there is something good there :) 

@iminashi 
I hope you will see what is wrong there :) 
It would be so great to have it working as it should and it would probably make CDLC even more clean ^^ ~

**Comment by cozy1** [comment]
@group chord density issues usually have to do with DDC.  If you are using old version of toolkit then you will have this issue.  Upgrade and be sure you are using DDC 3.4 or newer.

**Comment by cozy1** [comment]
@group chord density issues usually have to do with DDC. If you are using old version of toolkit then you will have this issue. Upgrade and be sure you are using DDC 3.4 or newer. Toolkit autogen's DDC now since all CDLC must have DDC to work properly in Remastered.

**Comment by iminashi** [comment]
@cozy1 Since this is about converting official DLC from SNG to XML back to SNG, DDC is not involved.

I've added a commit to my fork that should fix this issue for ODLC and not break anything too badly for CDLC. Still needs testing to be sure.

Here are some tests cases I could think of:
[Strum tests](https://drive.google.com/open?id=1s6EIDjDnx5lOjDK7zB2YnZ_l1YzTxHI3)

**Comment by cozy1** [comment]
@group Closed.  Plz PM each other on CF if you want to discuss further.

**Comment by cozy1** [comment]
@group Closed. Plz PM each other on CF if you want to discuss further.

**Comment by JustinAiken** [comment]
Ideally, XML<->SNG conversion would be completely loseless if there was no change.  Should be able to unpack/repack a file, and do a binary diff without any changes unless actual changes were made...

I end up using [pyrocksmith](https://github.com/0x0L/rocksmith) to unpack/repack DLCs that I want to make minor tweaks too
