### ISSUE TITLE
Packer filename issue

### ISSUE THREAD

**Issue by L0FKA** [rscustom/rocksmith-custom-song-toolkit#320]
Got report from user that he's unable to play manually created cdlc.
Digging in I've got invalid character in path.
this part of the cod could've use validation:
https://github.com/rscustom/rocksmith-custom-song-toolkit/blob/master/RocksmithToolkitLib/DLCPackage/Packer.cs#L645

Also may need to protect song key(dlc key?) from invalid chars more.?

**Comment by cozy1** [comment]
May want to check [latest commit](https://github.com/rscustom/rocksmith-custom-song-toolkit/tree/master) before spending much time on this.  It may be fixed now.

**Comment by L0FKA** [comment]
Reporting back. issue ain't fixed in latest commit build.

**Comment by L0FKA** [comment]
here's the file to reproduce the issue https://drive.google.com/open?id=1PqAA_eOszECUuYCbaoGjDRMESH3ZfAOB

**Comment by cozy1** [comment]
This CDLC was produced with an older version of the toolkit.  The CDLC has invalid '?' question marks in the toc entries, along with many other artifact file naming, and data corruption issues.  This is the result of the CDLC author using the invalid unicode 0131 (the dotless i) character, instead of valid ascii 'i'.  The current toolkit has validation methods that will prevent this type of corruption.  

You can [now use the toolkit](https://github.com/rscustom/rocksmith-custom-song-toolkit/commit/8c0983e6cacdcea3b038698256b1919d3b526e6c) to unpack and recover the corrupt artifacts from CDLC that have this type of corruption.  The unpacked CDLC must then be reauthored with the latest version of the toolkit to fix the errors.  This type of corruption must be manually repaired.
