### ISSUE TITLE
Cannot download any builds

### ISSUE THREAD

**Issue by syrusgreycloak** [rscustom/rocksmith-custom-song-toolkit#361]
Current build or older builds on builds tab (Windows) on rscustom.net generate same return message:

{"message":"Artifact not found or access denied."}

**Comment by ray** [comment]
Appveyor removes artifacts after 6 months. Since there hasn't been any activity in awhile to generate new builds they've all been removed.

A new build has been pushed & I published it as a github release which won't have the same 6 month limitation.
Stable builds should be released on github to avoid this in the future.
