### ISSUE TITLE
Verysign unable to sign latest build

### ISSUE THREAD

**Issue by L0FKA** [rscustom/rocksmith-custom-song-toolkit#368]
@ray I have some commits prepared to publish but appveyour log fir latest build states the current certificate is invalid? Please check if it's possible to fix it? 👀

**Comment by ray** [comment]
Certificate has been updated remotely.

If there are further issues I would recommend removing the code signing section of the appveyor build since in my opinion a self-signed cert does very little.
I'm unable to make any changes to the code going forward due to employer requirements & this project missing an explicit license.

**Comment by L0FKA** [comment]
I'm unable to selfishly decide on license for this project, would it be fine if we put MIT license of BSD ? 
I'm concerned about you employment contract and won't say much, so if it fails again I may drop certificate signing entirely, as you have suggested.

**Comment by oatkinson** [comment]
Have you guys looked into letsencrypt?  We have used it in azure and it has
been pretty convenient.
-Olin
