### ISSUE TITLE
Custom Song Toolkit lint broken

### ISSUE THREAD

**Issue by javipagan** [rscustom/rocksmith-custom-song-toolkit#369]
Hello, I'm trying to download it but link is broken in https://www.rscustom.net/
The page returns:
{"message":"Artifact not found or access denied."}

**Comment by ray** [comment]
It looks like appveyor changed artifact retention somewhat recently (https://www.appveyor.com/blog/2021/03/30/artifacts-retention-policy-update/)

Since new builds are pretty infrequent we should probably be creating new releases which can persist on github indefinitely.
We could also look into switching to github actions which can keep build artifacts for longer than appveyor does.

I manually rebuilt through appveyor and added the artifacts as a github release. Should be fine until the next build.
