### ISSUE TITLE
failed conversion: null zero issue

### ISSUE THREAD

**Issue by bobbobbin** [rscustom/rocksmith-custom-song-toolkit#380]
Hi [I will leave the LOG file, cheers]]
trying to rename the file info, and a fail warning popped up. occurred during both straight file conversion, and, also after unpacking/rebuilding file
TIA
Kindest regards

[_RSToolkit_2023-03-28.log](https://github.com/rscustom/rocksmith-custom-song-toolkit/files/11086715/_RSToolkit_2023-03-28.log)

**Comment by L0FKA** [comment]
Hello, do you have .Net framework 4.5or newer installed?
Is it able to generate any other package (cdlc) for you?
Logs has no clear indication of what exact problem is, all I can tell it's crashing because you're missing data... 
Check if your version field or any other fields in creator tab is empty.

Might be useful to know what cdlc you're trying to convert, so I could look it up locally?
Cheers!

**Comment by bobbobbin** [comment]
Hi,
According to my PC, there is net framework 4.8 advanced services and net framework 3.5 installed.
i've tried again, and all fields are filled in - same negative result
it is the beatles golden slumbers v2 file for windows that i'm trying to rename
Thanks for the quick reply!

**Comment by L0FKA** [comment]
Sorry that it took so long, converter tab works just fine. It's an issue with comments in xml file, when you generate metronome arrangement, which is dangerous to have since there's a limit to 5 arrangements. I can post a fix for this, but faster would be to uncheck "Create Metronome Bonus Arrangement" in edit arrangement form for +metronome arrangements.

**Comment by bobbobbin** [comment]
cheers - that did the trick! thanks very much!
